import React from 'react';
import { StyleSheet } from 'react-native';
const HomeStyle = StyleSheet.create({
  mainCantainer: { flex: 1, backgroundColor: 'white' },
  container: {
    paddingTop: 10,
    backgroundColor: '#fff',
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
    elevation: 5,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  profileIconContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButtons: { flexDirection: 'row', alignItems: 'center' },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: '#f0f0f0',
    borderRadius: 20,
    marginRight: 10,
  },
  addText: { color: '#0d1a3c', fontWeight: 'bold', marginLeft: 5 },
  translatorIconContainer: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  translator: { width: 30, height: 30, tintColor: 'grey' },
  searchBarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 25,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: 'lightgrey',
  },
  searchInput: { flex: 1, paddingVertical: 12, fontSize: 16, color: '#333' },
  searchIcon: { marginLeft: 10 },

  // 🔥 NEW STYLES
  menuRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 20,
    paddingHorizontal: 10,
  },
  menuItem: { alignItems: 'center', width: '23%' },
  menuText: { fontSize: 12, marginTop: 5, textAlign: 'center' },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff8e1',
    padding: 15,
    borderRadius: 12,
    margin: 10,
  },
  bannerText: { fontSize: 14, fontWeight: 'bold', marginBottom: 5 },
  chatBtn: {
    backgroundColor: '#fdd835',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginTop: 5,
  },
  chatBtnText: { fontWeight: 'bold', fontSize: 12 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 10,
    marginTop: 20,
  },
  astrologerCard: {
    alignItems: 'center',
    marginRight: 15,
    backgroundColor: '#f9f9f9',
    padding: 10,
    borderRadius: 10,
    width: 90,
  },
  astroName: { marginTop: 5, fontSize: 12 },
  offerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff8f0',
    padding: 15,
    borderRadius: 12,
    margin: 10,
  },
  offerText: { fontSize: 14, fontWeight: 'bold' },
  sessionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 10,
  },
  sessionBtn: {
    flex: 1,
    backgroundColor: '#fdd835',
    marginHorizontal: 5,
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  sessionBtnText: { fontWeight: 'bold', fontSize: 12 },
  sidebargirls: { width: 25, height: 25 },
  modalBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: 300,
    height: 300,
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 20,
    elevation: 20,
  },
  cardTitle: {
    fontWeight: 'bold',
    marginBottom: 15,
    fontSize: 18,
    textAlign: 'center',
  },
  langOption: {
    paddingVertical: 10,
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  selectedLangOption: { backgroundColor: 'lightyellow' },
  langText: { fontSize: 16, color: '#333', textAlign: 'center' },
  selectedLangText: { fontWeight: 'bold', color: '#000' },
  applyBtn: {
    backgroundColor: '#ffd700',
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 5,
  },
  crossButton: { borderRadius: 12, alignItems: 'flex-end', marginBottom: -5 },
  offerCardBlack: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'black',
    padding: 15,
    borderRadius: 12,
    margin: 10,
  },
  offerTitle: { color: 'white', fontWeight: 'bold', fontSize: 14 },
  offerSubtitle: { color: 'white', fontSize: 12 },
  chatNowYellow: {
    backgroundColor: '#fdd835',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 20,
  },
  viewAll: { fontSize: 12, color: 'grey' },

  sessionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    margin: 10,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  sessionAvatar: { width: 60, height: 60, borderRadius: 30 },
  sessionName: { fontWeight: 'bold', fontSize: 14 },
  sessionDate: { fontSize: 12, color: 'grey' },
  viewBtn: {
    borderWidth: 1,
    borderColor: '#fdd835',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    marginRight: 8,
  },
  chatAgainBtn: {
    backgroundColor: '#fdd835',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },

  astroCard: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginRight: 10,
    alignItems: 'center',
    width: 140,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  astroAvatar: { width: 70, height: 70, borderRadius: 35, marginBottom: 8 },
  // astroName: { fontWeight: "bold", fontSize: 14, textAlign: "center" },
  astroRate: { fontSize: 12, color: 'grey', marginBottom: 8 },
  chatBtnOutline: {
    borderWidth: 1,
    borderColor: 'green',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
});

export default HomeStyle;
